name: Run Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: laravel
          POSTGRES_USER: sail
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U sail -d laravel"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          cp .env.example .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "JWT_SECRET=testing-secret-key" >> .env

      - name: Start Laravel Sail
        run: |
          ./vendor/bin/sail up -d
          ./vendor/bin/sail artisan key:generate
        env:
          WWWUSER: 1001

      - name: Install dependencies
        run: ./vendor/bin/sail composer install --prefer-dist --no-progress --no-scripts --no-interaction

      - name: Run migrations
        run: ./vendor/bin/sail artisan migrate --env=testing --force

      - name: Execute tests
        run: ./vendor/bin/sail test --parallel

      - name: Stop Laravel Sail
        if: always()
        run: ./vendor/bin/sail down
