name: Run Unit Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.2, 8.3, 8.4 ]

    services:
      pgsql:
        image: postgres:17
        ports:
          - 5432:5432
        env:
            POSTGRES_DB: ${{ secrets.DB_DATABASE }}
            POSTGRES_USER: ${{ secrets.DB_USERNAME }}
            POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: >-
          --health-cmd "pg_isready -q -d testing -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring, zip, pdo_pgsql
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: composer install --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Prepare Laravel
        run: |
          cp .env.example .env
          cp .env.ci .env.testing
          php artisan key:generate
          php artisan jwt:secret --force

      - name: Run Migrations
        env:
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: php artisan migrate --force

      - name: Run Tests
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: vendor/bin/phpunit --log-junit phpunit-report.xml
