name: Main

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.2, 8.3, 8.4 ]
        laravel: [ 10, 11 ]
        dependency-version: [ prefer-lowest, prefer-stable ]

    name: Tests PHP${{ matrix.php }} - Laravel v${{ matrix.laravel }}
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: laravel
          POSTGRES_USER: sail
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U sail -d laravel"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, mbstring, zip, pdo, pdo_pgsql
          coverage: none

      - name: Cache Composer Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-L${{ matrix.laravel }}-${{ matrix.dependency-version }}-composer-${{ hashFiles('composer.json') }}

      - name: Install Composer Dependencies
        run: composer install --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Set Environment Variables
        run: |
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=laravel" >> .env
          echo "DB_USERNAME=sail" >> .env
          echo "DB_PASSWORD=password" >> .env
          echo "JWT_SECRET=$(php -r 'echo bin2hex(random_bytes(32));')" >> .env

      - name: Verify Environment File
        run: cat .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Clear Config Cache
        run: php artisan config:clear  # Ensure Laravel reads the updated .env

      - name: Set JWT Secret
        run: php artisan jwt:secret --force  # Fix for JWT not being set

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit --log-junit phpunit-report.xml

      - name: Upload PHPUnit Report
        uses: actions/upload-artifact@v4
        with:
          name: phpunit-report-php${{ matrix.php }}-laravel-${{ matrix.laravel }}-${{ matrix.dependency-version }}
          path: phpunit-report.xml
